### PR TITLE
Allow dirac to be disabled

### PR DESCRIPTION
**Pull request by scizo**
When dirac is disabled, it isn't added to the preloads and the agent
isn't started.

This allows someone to use the lower barrier to entry cljs-devtools formatters without having to worry about the dirac parts. The current main issue for us is that dirac is making a connection to the browser repl preventing us from creating our own connection to the browser repl.

### CODE REVIEW

**Comment by martinklepsch** [comment]
Making Dirac optional is a great idea IMHO 👍 

I'm even thinking a separate option flag `--enable-dirac` to enable Dirac (i.e. have it disabled by default) might be an option. Putting a `:disabled` key into a map seems like complecting two things: passing options to Dirac & disabling Dirac.

Generally it would also be interesting to make the task's namespaces work without Dirac namespaces being on the classpath so people can avoid the dependency all together.

**Comment by martinklepsch** [comment]
Looking at the code it seems that it might just work if we remove the `dirac-conf` require and wrap the `@start-dirac-once` ([line 86](https://github.com/boot-clj/boot-cljs-devtools/blob/master/src/powerlaces/boot_cljs_devtools.clj#L86)) in a `(when-not disabled ...)`.

@arichiardi is the requiring of `dirac-conf` necessary for some side effect to be ran?

**Comment by arichiardi** [comment]
We had some discussion about this on the Clojurians #dirac channel and while I see the problem, for me this task was a way to actually use Dirac more than just use `cljs-devtools` (which is a one line setup + nrepl start).

I am seeing though that folks are using this task with `cljs-devtools` only so (...reading Martin's answer...) I would be more than happy to accept the patch.

I like the idea above of adding an option but I would keep it enabled by default so that we don't invert the default behavior.

@martinklepsch no `dirac-conf` is a left-over of my attempt to give defaults (which are completely baked in dirac and not necessary here)

**Comment by arichiardi** [comment]
Actually I think all the current users chose the task because of the dirac feature.

**Comment by scizo** [comment]
I'll be happy to make the changes to add a --disable-dirac option instead of adding it into dirac-opts, as well as making it so that dirac is not a required dependency when it is disabled.

**Comment by arichiardi** [comment]
@scizo please go ahead and thanks!

**Comment by scizo** [comment]
When looking at doing the setup for cljs-devtools only, I was under the impression that I would still need to create a task that would add the preload. This feels like more than just a simple one liner. Am I missing something @arichiardi?

**Comment by arichiardi** [comment]
Well `:preloads` is a compiler option so you don't strictly need a task for that, you could just add it to your `cljs` task under `:compiler-options`. Exactly what we are doing here. Am I missing something of your use case?

**Comment by martinklepsch** [comment]
> and I don't think a task for cljs-devtools would be valuable..it is so easy to add it to an existing code base...a task is a bit overkill. [via Slack]

I'm using boot-cljs-devtools in two projects solely for cljs-devtools, not using Dirac at all. By wrapping it up in a task it nicely integrates with the boot pipeline and allows you to keep development related concerns out of your production code. So I think it does add value to package it up in a task.

As Antonin mentioned a few times Dirac is somewhat advanced and requires a good bit more setup outside of Boot/Clojure so `cljs-devtools` is what you can get for free with no effort when just starting a new project. (In fact I think I'll probably add it to Tenzing.)

In my thinking it seems more appropriate to have the advanced feature behind a flag. This task is very young still so I'm trying to argue for the people that come new to CLJS, just want to improve their development experience with low cost/high gain (cljs-devtools) and don't want to take the time to configure Dirac (high cost/high gain). The version numbers of this project clearly indicate that this kind of breakage is within bounds :)

**Comment by scizo** [comment]
It just didn't occur to me to add it through the `cljs` task, which is obvious now that you say it. I understand your hesitancy to make disabling dirac an option now. If you aren't sure about this change I can hold off.

**Comment by scizo** [comment]
I do agree with @martinklepsch that a simple task to add cljs-devtools is nicer than explicitly adding the the preload with the cljs task.

**Comment by arichiardi** [comment]
Well Martin is kind of right, and @darwin was always saying that Dirac is for pros, but also this can be a good task for ease the access to it (maybe it can install the Dirac plugin for you?).

Also, given the stats, we can break it: `10 Downloads 4 This Version`.

So let's brainstorm, would maybe a separate task for dirac work better at this point?

**Comment by arichiardi** [comment]
Separation seems like a good thing, also following boot/unix philosophy of one task one responsibility.

**Comment by martinklepsch** [comment]
@arichiardi I think packaging it in one jar is great because it "makes the way towards Dirac shorter" but maybe a `cljs-devtools` and a `dirac` task (same project/namespace) would be a good level of separation?

**Comment by arichiardi** [comment]
@martinklepsch yes I guess at this point we are all saying the same thing :+1: whoever is free first can go ahead and have a look at it, please let's just write here so that we don't du/triplicate our efforts.

**Comment by darwin** [comment]
I would propose to have two separate tasks. One for cljs-devtools and one for dirac (without cljs-devtools). 

And implement a check in dirac task suggesting using cljs-devtools as well if it is missing with option to silence the warning (not sure how hard this would be with boot).

With this setup people could mix both tasks freely.

**Comment by pepe** [comment]
I just added #7 which separates tasks, as proposed by @darwin. Please look at the patch, as I am total noob in all of this.

Thank you very much.

**Comment by arichiardi** [comment]
@pepe thanks a lot! Will do 😀
@scizo I am closing this in the meantime

**Pull request closed without merging**
